module.exports = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    FETCH_ME_SUCCESS: 'FETCH_ME_SUCCESS',
    LOGOUT: 'LOGOUT',
    REGISTER_ERROR: 'REGISTER_ERROR',
    CLEAR_REGISTER_SUCCESS_MESSAGE: 'CLEAR_REGISTER_SUCCESS_MESSAGE',
    CLEAR_REGISTER_ERROR_MESSAGE: 'CLEAR_REGISTER_ERROR_MESSAGE',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    CLEAR_LOGIN_ERROR_MESSAGE: 'CLEAR_LOGIN_ERROR_MESSAGE',
    SET_TOKEN: 'SET_TOKEN'
};