module.exports = {
    LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
    SINGLE_TODO_SUCCESS: 'SINGLE_TODO_SUCCESS',
    CREATE_TODO_SUCCESS: 'CREATE_TODOS_SUCCESS',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS'
};